###############################################################################
# Package: ha_config_local_git
# Description: Sensors for local Home Assistant Config git repo
###############################################################################

command_line:
  - sensor:
      # Read the last local git log
      name: config_current_commit
      command: cd /config; git log -1 --date=iso-strict
      scan_interval: 3600 # every hour

template:
  - sensor:
      # First 7 characters of the current commit id
      - name: config_current_commit_id
        state: >-
          {{ states('sensor.config_current_commit').split()[1][:7] }}

      # The date/time of the current commit
      - name: config_current_commit_datetime
        state: >-
          {% set lines = states('sensor.config_current_commit').split('\n') %}
          {{ lines[2].split('Date:')[1].strip() }}

      # Human readable time since current commit
      - name: config_time_since_last_commit
        state: >-
          {{ time_since(as_datetime(states('sensor.config_current_commit_datetime'))) }} ago

      # Commit message of current commit
      - name: config_current_commit_message
        state: >-
          {{ states('sensor.config_current_commit').split('\n')[4] }}